Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebAppProyectoFinal.Models;
using WebAppProyectoFinal.Services;

namespace WebAppProyectoFinal.Controllers
{
    public class AdminController : Controller
    {
        private readonly IAdmin _admin;
        public AdminController(IAdmin admin)
        {
            _admin = admin;
        }
        [Route("Admin/AdminIndex")]
        public IActionResult AdminIndex()
        {
            return View();
        }
        public IActionResult Validar(TbAdmin admin)
        {
            if (ModelState.IsValid)
            {
                if (_admin.ValidateLogin(admin) == true)
                {
                    HttpContext.Session.SetString("sAdmin", JsonConvert.SerializeObject(admin));
                    return RedirectToAction("AdminView", "Libro");
                }
                else
                {
                    return View("AdminIndex");
                }
            }
            else
            {
                return View("AdminIndex");
            }
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebAppProyectoFinal.Models;
using WebAppProyectoFinal.Services;

namespace WebAppProyectoFinal.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogin _login;
        public LoginController(ILogin login)
        {
            _login = login;
        }
        public IActionResult LoginIndex()
        {
            return View();
        } 
        public IActionResult Validar(TbLogin login1)
        {
            if (ModelState.IsValid)
            {
                if (_login.ValidateLogin(login1) == true)
                {
                    HttpContext.Session.SetString("sUsuario", JsonConvert.SerializeObject(login1));
                    return RedirectToAction("LibroIndex", "Libro");
                }
                else
                {
                    return View("LoginIndex");
                }
            }
            else
            {
                return View("LoginIndex");
            }
        }
        public IActionResult CerrarSesion()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("LoginIndex");
        }
    }
}

Controllers/TemporalReservaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient.DataClassification;
using Newtonsoft.Json;
using WebAppProyectoFinal.Models;
using WebAppProyectoFinal.Services;

namespace WebAppProyectoFinal.Controllers
{
    public class TemporalReservaController : Controller
    {
        private readonly ITemporalReserva _temporalReserva;
        public TemporalReservaController(ITemporalReserva temporalReserva)
        {
            _temporalReserva = temporalReserva;
        }

        public IActionResult Index(string txtid,
                                   string txttitulo,
                                   string txtgenero,
                                   string txtautor,
                                   string txtaño,
                                   string txtstock,
                                   string txtcantidad)
        {
            if(_temporalReserva.validarDatos(int.Parse(txtid)) == true)
            {
                TemporalReserva obj = new TemporalReserva();
                obj.id = int.Parse(txtid);
                obj.titulo = txttitulo;
                obj.genero = txtgenero;
                obj.autor = txtautor;
                obj.año = txtaño;
                obj.stock = int.Parse(txtstock);
                obj.cantidad = int.Parse(txtcantidad);
                _temporalReserva.add(obj);
                return RedirectToAction("LibroIndex", "Libro");
            }
            else
            {
                return RedirectToAction("Reservar", "Libro", new { codigo = int.Parse(txtid) });
            }
        }
        public IActionResult VerReservas()
        {
            var objSession = HttpContext.Session.GetString("sUsuario");
            if (objSession != null)
            {
                var obj = JsonConvert.DeserializeObject<TbLogin>(HttpContext.Session.GetString("sUsuario"));
                ViewBag.idCli = obj.getIdCliente();
                return View(_temporalReserva.GetAllTemporaryBookings());
            }
            else
            {
                return RedirectToAction("LoginIndex", "Login");
            }
        }
        public IActionResult Eliminar(int id)
        {
            _temporalReserva.eliminar(id);
            return RedirectToAction("LibroIndex", "Libro");
        }
        public IActionResult AgregarDetalle(TbReserva reserva)
        {
            _temporalReserva.agregarTemporal(reserva);
            return RedirectToAction("LibroIndex", "Libro");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppProyectoFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppProyectoFinal.styles.css" asp-append-version="true" />
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Libro" asp-action="LibroIndex"> Catálogo Libros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TemporalReserva" asp-action="VerReservas">Ver Reservas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdminIndex">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Iniciar Sesión Administrador
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="CerrarSesion">
                                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Cerrar Sesión
                            </a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>