Controllers/DetalleController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppProyectoFinal.Services;

namespace WebAppProyectoFinal.Controllers
{
    public class DetalleController : Controller
    {
        private readonly IDetalle _detalle;
        public DetalleController(IDetalle detalle)
        {
            _detalle = detalle;
        }
        public IActionResult VerDetalles()
        {
            return View(_detalle.GetAllDetails());
        }
        [Route("Detalle/VerDetalle/{codigo}")]
        public IActionResult VerDetalle(int codigo)
        {
            return View(_detalle.GetDetalleById(codigo));
        }
    }
}

Controllers/LibroController.cs
using WebAppProyectoFinal.Models;
using Microsoft.AspNetCore.Mvc;
using WebAppProyectoFinal.Services;
using Newtonsoft.Json;

namespace WebAppProyectoFinal.Controllers
{
    public class LibroController : Controller
    {
        private readonly ILibro _libro;
        public LibroController(ILibro libro)
        {
            _libro = libro;
        }
        public IActionResult LibroIndex()
        {
            var objSession = HttpContext.Session.GetString("sUsuario");
            if (objSession != null)
            {
                var obj = JsonConvert.DeserializeObject<TbLogin>(HttpContext.Session.GetString("sUsuario"));
                ViewBag.nombreUsuario = obj.getNomCli();
                //retornando los datos del producto a través del objeto
                return View(_libro.GetAllBooks());
            }
            else
            {
                return RedirectToAction("LoginIndex", "Login");
            }
        }
        [Route("Libro/Reservar/{codigo}")]
        public IActionResult Reservar(int codigo)
        {
            var objObtenido = _libro.GetLibro(codigo);
            return View(objObtenido);
        }
        public IActionResult AdminView()
        {
            var objSession = HttpContext.Session.GetString("sAdmin");
            if (objSession != null)
            {
                var obj = JsonConvert.DeserializeObject<TbAdmin>(HttpContext.Session.GetString("sAdmin"));
                ViewBag.nombreUsuario = obj.UserAdmin;
                //retornando los datos del producto a través del objeto
                return View(_libro.GetAllBooks());
            }
            else
            {
                return RedirectToAction("AdminIndex", "Admin");
            }
        }
        public IActionResult Nuevo()
        {
            return View();
        }
        public IActionResult Grabar(TbLibro obj)
        {
            _libro.add(obj);
            return RedirectToAction("AdminView");
        }
        [Route("Libro/Eliminar/{codigo}")]
        public IActionResult Eliminar(int codigo)
        {
            _libro.remove(codigo);
            return RedirectToAction("AdminView");
        }
        [Route("Libro/Modificar/{codigo}")]
        public IActionResult Modificar(int codigo)
        {
            return View(_libro.edit(codigo));
        }

        public IActionResult ModificarLibro(TbLibro libro)
        {
            _libro.editDetails(libro);
            return RedirectToAction("AdminView");
        }
    }
}

Controllers/ReservaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;
using WebAppProyectoFinal.Models;
using WebAppProyectoFinal.Services;

namespace WebAppProyectoFinal.Controllers
{
    public class ReservaController : Controller
    {
        private readonly IReserva _reserva;
        public ReservaController(IReserva reserva)
        {
            _reserva = reserva;
        }
        public IActionResult VerBoleta(string txtfechaA,
                                       string txtfechaD,
                                       string txtidCli,
                                       string txtestado)
        {
            TbReserva obj = new TbReserva();
            obj.FecPrestamo = txtfechaA;
            obj.FecDevolucion = txtfechaD;
            obj.IdCli = int.Parse(txtidCli);
            obj.Estado = txtestado;
            _reserva.add(obj);
            return View(obj);
        }
        public IActionResult ViewBookings()
        {
            return View(_reserva.GetAllBookings());
        }
    }
}

Controllers/TemporalReservaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient.DataClassification;
using Newtonsoft.Json;
using WebAppProyectoFinal.Models;
using WebAppProyectoFinal.Services;

namespace WebAppProyectoFinal.Controllers
{
    public class TemporalReservaController : Controller
    {
        private readonly ITemporalReserva _temporalReserva;
        public TemporalReservaController(ITemporalReserva temporalReserva)
        {
            _temporalReserva = temporalReserva;
        }

        public IActionResult Index(string txtid,
                                   string txttitulo,
                                   string txtgenero,
                                   string txtautor,
                                   string txtaño,
                                   string txtstock,
                                   string txtcantidad)
        {
            if(_temporalReserva.validarDatos(int.Parse(txtid)) == true)
            {
                TemporalReserva obj = new TemporalReserva();
                obj.id = int.Parse(txtid);
                obj.titulo = txttitulo;
                obj.genero = txtgenero;
                obj.autor = txtautor;
                obj.año = txtaño;
                obj.stock = int.Parse(txtstock);
                obj.cantidad = int.Parse(txtcantidad);
                _temporalReserva.add(obj);
                return RedirectToAction("LibroIndex", "Libro");
            }
            else
            {
                return RedirectToAction("Reservar", "Libro", new { codigo = int.Parse(txtid) });
            }
        }
        public IActionResult VerReservas()
        {
            var objSession = HttpContext.Session.GetString("sUsuario");
            if (objSession != null)
            {
                var obj = JsonConvert.DeserializeObject<TbLogin>(HttpContext.Session.GetString("sUsuario"));
                ViewBag.idCli = obj.getIdCliente();
                return View(_temporalReserva.GetAllTemporaryBookings());
            }
            else
            {
                return RedirectToAction("LoginIndex", "Login");
            }
        }
        public IActionResult Eliminar(int id)
        {
            _temporalReserva.eliminar(id);
            return RedirectToAction("LibroIndex", "Libro");
        }
        public IActionResult AgregarDetalle(TbReserva reserva)
        {
            _temporalReserva.agregarTemporal(reserva);
            return RedirectToAction("LibroIndex", "Libro");
        }
    }
}

Views/Libro/AdminView.cshtml
@model IEnumerable<WebAppProyectoFinal.Models.TbLibro>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        
    </head>
    <body>
        <h2>
            <a asp-controller="Reserva" asp-action="ViewBookings" class="btn btn-info">
                <span class="glyphicon glyphicon-eye-open"></span> Ver Reservas
            </a>
        </h2>
        <h2>
            <a asp-controller="Detalle" asp-action="VerDetalles" class="btn btn-info">
                <span class="glyphicon glyphicon-eye-open"></span> Ver Detalles
            </a>
        </h2>
        <h2><a asp-action="Nuevo" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span> Nuevo Libro
            </a>
        </h2>
        <h3 class="alert-primary">Listado de libros</h3>
        <table class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>Titulo</td>
                <td>Genero</td>
                <td>Autor</td>
                <td>Año</td>
                <td>Stock</td>
            </tr>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.IdLibro</td>
                    <td>@item.Titulo</td>
                    <td>@item.Genero</td>
                    <td>@item.Autor</td>
                    <td>@item.Año</td>
                    <td>@item.Stock</td>
                    <td><a asp-action="Eliminar" asp-route-id="@item.IdLibro" 
                        onclick="return confirmarEliminar()" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span> Eliminar
                        </a>
                    </td>
                    <td><a asp-action="Modificar" asp-route-id="@item.IdLibro"
                     class="btn btn-info">
                            <span class="glyphicon glyphicon-pencil"></span> Modificar
                        </a>
                    </td>
                </tr>
            }
        </tbody>
        </table>
    </body>
</html>
<script type="text/javascript" src="~/js/confirmaciones.js"></script>

Views/Libro/LibroIndex.cshtml
@model IEnumerable<WebAppProyectoFinal.Models.TbLibro>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,600,700,800" rel='stylesheet' type='text/css'>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
        <link rel="stylesheet" href="~/css/libro.css" />
    </head>
    <body>
        <!--Div de las herramientas de busqueda-->
        <h2 class="alert-warning">Bienvenido(a): @ViewBag.nombreUsuario</h2>
        <div class="herramientas">
            <div class="buscar-area">
                <input type="text" id="buscar" placeholder="Buscar título" onkeyup="buscar()" />
                <button id="btnBuscar">Buscar</button>
            </div>
        </div>
    <div class="libros libros-tabla row" id="buscar-libros">
        <div class="col-sm-12 mb-3" id="contenedor2">
        @foreach (var item in Model)
        {
            <div class="contenedor">
                <div class="libro">
                    <div class="libro-img">
                        <img src="@item.Link">
                    </div>
                    <div class="libro-content">
                        <h3 class="titulo">
                            @item.Titulo
                        </h3>
                        <h3 class="autor">
                            <small>@item.Autor</small>
                        </h3>
                        <p class="libro-texto stock">Stock: @item.Stock</p>
                        <p class="libro-texto año">Año: @item.Año</p>
                        <a asp-action="Reservar" asp-route-id="@item.IdLibro" class="btn btn-primary">Reservar</a>
                    </div>
                </div>
            </div>
        }
        </div>
    </div>
    </body>
</html>
<script type="text/javascript" src="~/js/buscar.js"></script>

Views/Libro/Modificar.cshtml
@model WebAppProyectoFinal.Models.TbLibro
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <form asp-controller="Libro" asp-action="ModificarLibro" method="post">
        <input type="hidden" asp-for="IdLibro" />
        Titulo<input type="text" asp-for="Titulo" class="form-control" placeholder="Ingrese el titulo" />
        Genero<input type="text" asp-for="Genero" class="form-control" placeholder="Ingrese el genero" />
        Autor<input type="text" asp-for="Autor" class="form-control" placeholder="Ingrese el autor" />
        Año<input type="text" asp-for="Año" class="form-control" placeholder="Ingrese el año" />
        Stock<input type="number" asp-for="Stock" class="form-control" placeholder="Ingrese el stock" />
        Link<input type="text" asp-for="Link" class="form-control" placeholder="Ingrese el link de la portada" />
        <button type="submit" class="btn btn-info" onclick="return confirmarModificar()">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Modificar
        </button>
    </form>
</body>
</html>
<script type="text/javascript" src="~/js/confirmaciones.js"></script>

Views/Libro/Nuevo.cshtml
@model WebAppProyectoFinal.Models.TbLibro
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>

</head>
<body>
    <form asp-controller="Libro" asp-action="Grabar" method="post">
        Titulo<input type="text" asp-for="Titulo" class="form-control" placeholder="Ingrese el titulo" />
        Genero<input type="text" asp-for="Genero" class="form-control" placeholder="Ingrese el genero" />
        Autor<input type="text" asp-for="Autor" class="form-control" placeholder="Ingrese el autor" />
        Año<input type="text" asp-for="Año" class="form-control" placeholder="Ingrese el año" />
        Stock<input type="number" asp-for="Stock" class="form-control" placeholder="Ingrese el stock" />
        Link<input type="text" asp-for="Link" class="form-control" placeholder="Ingrese el link de la portada" />
        <button type="submit" class="btn btn-success" onclick="return confirmarNuevo()">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar
        </button>
    </form>
</body>
</html>
<script type="text/javascript" src="~/js/confirmaciones.js"></script>

Views/Libro/Reservar.cshtml
@model WebAppProyectoFinal.Models.TbLibro
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="~/css/reservar.css" />
    </head>
    <body>
        <div class="row mt-5">
            <div class="col-lg-5 col-md-12 col-12">
                <img src="@Model.Link" class="img-fluid w-75 h-100" height="312" width="170" />
            </div>
            <div class="col-lg-6 col-md-12 col-12">
                <h1>@Model.Titulo</h1>
                <h2 class="py-4">Autor: @Model.Autor</h2>
                <h3>Género: @Model.Genero</h3>
                <h3>Stock: @Model.Stock</h3>
                <form class="formulario" asp-controller="TemporalReserva" asp-action="Index" method="post">
                    <input type="hidden" name="txtid" value="@Model.IdLibro" />
                    <input type="hidden" name="txttitulo" value="@Model.Titulo" />
                    <input type="hidden" name="txtgenero" value="@Model.Genero" />
                    <input type="hidden" name="txtautor" value="@Model.Autor" />
                    <input type="hidden" name="txtaño" value="@Model.Año" />
                    <input type="hidden" name="txtstock" value="@Model.Stock" />
                    <input type="number" name="txtcantidad" value="1" min="1" max="@Model.Stock" required/>
                    <span class="validity"></span>
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Reservar Libro
                    </button>
                    <h5 class="text-danger">Advertencia! Los libros NO se pueden repetir</h5>
                </form>
            </div>
        </div>
        
        
    </body>
</html>